/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package empresa;

import DAO.Conexao;
import Model.Cliente;
import Model.Produto;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vini2
 */
public class Consultar_Estoque extends javax.swing.JFrame {

    /**
     * Creates new form Consultar_Estoque
     */
    public Consultar_Estoque() {
        initComponents();
        DefaultTableModel modelo =(DefaultTableModel) t1.getModel(); 

        modelo.setNumRows(0);
        
        
        
        try {
            Connection conexao = (Connection) Conexao.getConnection();
            String sql = "SELECT * FROM produto;";
            
            java.sql.PreparedStatement statement = conexao.prepareStatement(sql);
             ArrayList<Produto> produtos = new ArrayList<Produto>();
        
        statement.execute();
        ResultSet result = statement.getResultSet();
        
        while(result.next()){
            String nome = result.getString("nome");
            int cod = result.getInt("cod_produto");
            int quant = result.getInt("quant_produto");
            int preço = result.getInt("preço");;
           
            
            
            Produto func = new Produto(cod, nome, preço, quant);
           
            
            produtos.add(func);
           
            
        }
        
       
        int count = produtos.size();
        int i;
        for(i=0;i<count;i++){
            modelo.addRow(new Object[]{produtos.get(i).getCod_produto(),produtos.get(i).getNome(),produtos.get(i).getPreco(),produtos.get(i).getQuantidade()});
        }
         
          
            
        
        

        } catch (SQLException ex) {
            Logger.getLogger(Consultar_Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cod = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estoque");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));
        getContentPane().add(cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 207, -1));

        jButton1.setText("Busca");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Codigo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));
        getContentPane().add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 207, -1));

        jButton2.setText("Busca");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Estoque");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Pesquisa por:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        t1.setBackground(new java.awt.Color(0, 0, 0));
        t1.setForeground(new java.awt.Color(255, 255, 255));
        t1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Preço", "Quantidade"
            }
        ));
        t1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(t1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 420, 240));

        jButton4.setText("Visualizar Todos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/empresa/imagens/Fundo.jpeg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel modelo =(DefaultTableModel) t1.getModel(); 
         modelo.setNumRows(0);
        
        
        
        try {
            Connection conexao = (Connection) Conexao.getConnection();
            String sql = "SELECT * FROM produto WHERE cod_produto = ?;";
            
            java.sql.PreparedStatement statement = conexao.prepareStatement(sql);
             ArrayList<Produto> produtos = new ArrayList<Produto>();
             statement.setInt(1,Integer.parseInt(this.cod.getText()));
        
        statement.execute();
        ResultSet result = statement.getResultSet();
        
        while(result.next()){
            int cod  = result.getInt("cod_produto");
            String nome = result.getString("nome");
            int preço = result.getInt("preço");
            int quant = result.getInt("quant_produto");
           
            
            
            Produto func = new Produto(cod, nome, preço, quant);
           
            
            produtos.add(func);
           
            
        }
        
       
        int count = produtos.size();
        int i;
        for(i=0;i<count;i++){
            modelo.addRow(new Object[]{produtos.get(i).getCod_produto(),produtos.get(i).getNome(),produtos.get(i).getPreco(),produtos.get(i).getQuantidade()});
        }
         
          
            
        
        

        } catch (SQLException ex) {
            Logger.getLogger(Consultar_Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          
       Tela_Funcionario telafunc = new Tela_Funcionario();
       telafunc.setVisible(true);
       
       Consultar_Estoque.this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         DefaultTableModel modelo =(DefaultTableModel) t1.getModel(); 
         modelo.setNumRows(0);
        
        
        
        try {
            Connection conexao = (Connection) Conexao.getConnection();
            String sql = "SELECT * FROM produto WHERE nome like ?;";
            
            java.sql.PreparedStatement statement = conexao.prepareStatement(sql);
             ArrayList<Produto> produtos = new ArrayList<Produto>();
             statement.setString(1,this.nome.getText());
        
        statement.execute();
        ResultSet result = statement.getResultSet();
        
        while(result.next()){
            int cod  = result.getInt("cod_produto");
            String nome = result.getString("nome");
            int preço = result.getInt("preço");
            int quant = result.getInt("quant_produto");
           
            
            
            Produto func = new Produto(cod, nome, preço, quant);
           
            
            produtos.add(func);
           
            
        }
        
       
        int count = produtos.size();
        int i;
        for(i=0;i<count;i++){
            modelo.addRow(new Object[]{produtos.get(i).getCod_produto(),produtos.get(i).getNome(),produtos.get(i).getPreco(),produtos.get(i).getQuantidade()});
        }
         
          
            
        
        

        } catch (SQLException ex) {
            Logger.getLogger(Consultar_Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void t1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t1MouseClicked
      
        cod.setText(t1.getValueAt(t1.getSelectedRow(),0).toString());
         nome.setText(t1.getValueAt(t1.getSelectedRow(),1).toString());
        
    }//GEN-LAST:event_t1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel modelo =(DefaultTableModel) t1.getModel(); 
         modelo.setNumRows(0);
        
        
        
        try {
            Connection conexao = (Connection) Conexao.getConnection();
            String sql = "SELECT * FROM produto;";
            
            java.sql.PreparedStatement statement = conexao.prepareStatement(sql);
             ArrayList<Produto> produtos = new ArrayList<Produto>();
             
        
        statement.execute();
        ResultSet result = statement.getResultSet();
        
        while(result.next()){
            int cod  = result.getInt("cod_produto");
            String nome = result.getString("nome");
            int preço = result.getInt("preço");
            int quant = result.getInt("quant_produto");
           
            
            
            Produto func = new Produto(cod, nome, preço, quant);
           
            
            produtos.add(func);
           
            
        }
        
       
        int count = produtos.size();
        int i;
        for(i=0;i<count;i++){
            modelo.addRow(new Object[]{produtos.get(i).getCod_produto(),produtos.get(i).getNome(),produtos.get(i).getPreco(),produtos.get(i).getQuantidade()});
        }
         
          
            
        
        

        } catch (SQLException ex) {
            Logger.getLogger(Consultar_Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultar_Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultar_Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultar_Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultar_Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultar_Estoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cod;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nome;
    private javax.swing.JTable t1;
    // End of variables declaration//GEN-END:variables
}
